### ISSUE TITLE
Is this binding complete?

### ISSUE THREAD

**Issue by danilolekovic** [Calrama/llvm-d#10]
Hi!

Great job with this project! Is the binding complete? I've been trying to translate [this line of code](https://github.com/d11wtq/kaleidoscope/blob/master/ast.cpp#L75) into D for about an hour now with no luck. Any ideas? Sorry for creating an issue, did not know where to ask for support.

**Comment by danilolekovic** [comment]
Got it:

`return LLVMConstReal(LLVMDoubleType(), value);`

**Comment by Calrama** [comment]
No worries, in the future, you can contact me at the email adress (now) listed in my profile.
