### ISSUE TITLE
lto_codegen_add prototype mismatch

### ISSUE THREAD

**Issue by daym** [Calrama/llvm-d#19]
https://github.com/Calrama/llvm-d/blob/master/source/llvm/functions.d#LC1488 conflicts with the declaration two lines below it. That causes a build failure when compiled with ldc 1.1.0 and llvm >= 3.7.0.

**Comment by Calrama** [comment]
Thanks for the report, should work now.

**Comment by daym** [comment]
Hmm... does it always return bool in llvm now?

**Comment by Calrama** [comment]
See the commit message above. [The void was wrong](https://github.com/llvm-mirror/llvm/blob/master/include/llvm-c/lto.h#L379).

**Comment by daym** [comment]
Yeah, thanks!
