### ISSUE TITLE
New LLVM versions

### ISSUE THREAD

**Issue by blm768** [Calrama/llvm-d#7]
The C API isn't currently configured to allow linking to recent LLVM releases (i.e. 3.7). I can add the new versions (at least in versions.d) and submit a pull request if you'd like.

**Comment by Calrama** [comment]
I do welcome a PR for this, but if you do not add the relevant C API changes you will most likely run into problems, since quite a bit of functionality was added/removed/changed over the last versions of LLVM and just patching llvm-d to load the new shared lib will not factor that in. You'd have to diff the headers of the new versions against the latest released one and add the changes iteratively (download the relevant release tarballs and diff the include/llvm-c directores recursively).

**Comment by blm768** [comment]
I'll try to play with that when I get the chance. I'm working on several other projects, so it may take a bit of time.

**Comment by blm768** [comment]
It looks like 3.5 deprecated some multithreading functions. Do we want to mark them as deprecated in the bindings (conditional on the version, of course) or just rely on the user to know they're being phased out?

**Comment by Calrama** [comment]
Well, the way I planned for something like this was with annotating them like shown  [here](https://github.com/Calrama/llvm-d/blob/master/llvm/c/functions.d#L961) and [here](https://github.com/Calrama/llvm-d/blob/master/llvm/c/functions.d#L967). However, I never got around to finishing the [mixin](https://github.com/Calrama/llvm-d/blob/master/llvm/c/functions.d#L14) invocation to allow the specification of both "-" and "+". That should be fixable by changing [this](https://github.com/Calrama/llvm-d/blob/master/llvm/c/functions.d#L17) line from
```d
((signature[1] == "-") && (to!float(signature[2]) > LLVM_Version)))
```

to something like
```d
((signature[1] == "-") && (to!float(signature[2]) > LLVM_Version)) ||
((signature.length == 5) && (signature[1] == "+") && (to!float(signature[2]) <= LLVM_Version) && (signature[3] == "-") && (to!float(signature[4]) > LLVM_Version)))
```

After that, you just need to e.g. change 
```d
"LLVMStartMultithreaded" : ["LLVMBool function()",
	                            "+", "3.3"],
```

to
```d
"LLVMStartMultithreaded" : ["LLVMBool function()",
	                            "+", "3.3", "-", "3.5"],
```

**Comment by blm768** [comment]
I've got it up to 3.5.0 now. I'll get started on 3.5.1.

**Comment by Calrama** [comment]
Cool, thank you for the update.

**Comment by blm768** [comment]
3.6 should be ready. I'll submit a PR so you can look at it, and in the meantime, I'll start on 3.7.

**Comment by Calrama** [comment]
PR for 3.6 has been merged.

**Comment by blm768** [comment]
I just realized that I forgot to set LLVM_Version while doing my test compiles, so there are some minor issues...

I've mostly ironed out 3.5, though.

**Comment by blm768** [comment]
OK; it should be basically done. The only things left are:
- How do we update LLVMC_TargetCapabilities? Do we just glean the data from the release notes?
- Should the default LLVM version be increased to something like 3.6 or 3.7?

**Comment by Calrama** [comment]
- IIRC this is what I did to populate LLVMC_TargetCapabilities: Do a complete build of LLVM (everything enabled, so all that LLVM release supports gets built) and then grep the resulting shared library's symbol table.
- The default should be the highest supported version

**Comment by blm768** [comment]
Ew, nasty. ;) At least on my Arch Linux system, target-specific stuff seems to be broken up into a bunch of static libraries (i.e. /usr/lib/libLLVMX86Disassembler.a), so I should be able to pull a lot of stuff from that. I think that Arch builds LLVM with everything turned on, although I'm not completely sure about that.

**Comment by Calrama** [comment]
PR has been merged, so I will close this. Thank you again for your contribution.
